// Получение вопросов теста
export const GET_TEST_QUESTIONS_SUCCESS = 'GET_TEST_QUESTIONS_SUCCESS';
export const GET_TEST_QUESTIONS_RECEIVED = 'GET_TEST_QUESTIONS_RECEIVED';
export const GET_TEST_QUESTIONS_ERROR = 'GET_TEST_QUESTIONS_ERROR';